export const Config = 
{
URL:'https://api.docshafa.ir/api',

    Defination:{
        GetUnit:'/GetUnits',
        GetFiscalYear:'/GetFiscalYears',
        GetSets:'/GetSets',
        GetUsersWithUsernameandPass:'/GetUsersWithUsernameandPass',
        GetProducts:'/GetProducts',
        GetPosts:'/GetPosts',
        GetAllUsers:'/GetAllUsers',
        GetPostsAccessParts:'/GetPostsAccessParts',
        GetSetsOfProducts:'/GetSetsOfProducts',
        GetGroupOfSets:'/GetGroupOfSets',
        GetGroups:'/GetGroups',
        GetStates:'/GetStates',
        GetParts:'/GetParts',
        GetProductsDocuments:'/GetProductsDocuments',
        GetProductsDocumentsWithId:'/GetProductsDocumentsWithId',
        GetSetsDocumentsWithId:'/GetSetsDocumentsWithId',
        GetProductDocumentData:'/GetProductDocumentData',
        GetSetsDocumentData:'/GetSetsDocumentData',
        GetUserAccessParts:'/GetUserAccessParts',
        GetKardex:'/GetKardex',
        GetKardexSets:'/GetKardexSets',
        GetSetsDocuments:'/GetSetsDocuments',
        AddUnit:'/AddUnits',
        AddUsersAccessParts:'/AddUsersAccessParts',
        AddSetsOfProduct:'/AddSetsOfProduct',
        AddDocumentControls:'/AddDocumentControls',
        UpdateDocumentControls:'/UpdateDocumentControls',
        AddProductDocuments:'/AddProductDocuments',
        AddSetsDocuments:'/AddSetsDocuments',
        AddGroupOfSets:'/AddGroupOfSets',
        AddUsers:'/AddUsers',
        AddFiscalYear:'/AddFiscalYears',
        AddSets:'/AddSets',
        AddParts:'/AddParts',
        AddProducts:'/AddProducts',
        AddPosts:'/AddPosts',
        AddGroups:'/AddGroups',
        AddStates:'/AddStates',
        DeleteUnits:'/DeleteUnits',
        DeleteFiscalYear:'/DeleteFiscalYear',
        DeleteSets:'/DeleteSets',
        DeleteParts:'/DeleteParts',
        DeleteGroups:'/DeleteGroups',
        DeleteUsersAccessParts:'/DeleteUsersAccessParts',
        DeleteSetsOfProduct:'/DeleteSetsOfProduct',
        DeleteGroupOfSets:'/DeleteGroupOfSets',
        DeleteUsersWithUsername:'/DeleteUsersWithUsername',
        DeletePosts:'/DeletePosts',
        DeleteStates:'/DeleteStates',
        DeleteProducts:'/DeleteProducts',
        ResetPassword:'/ResetPassword',
        DeleteDocumentControlsSets:'/DeleteDocumentControlsSets',
        DeleteDocumentControlsProduct:'/DeleteDocumentControlsProduct',
        DeleteDocumentControls:"/DeleteDocumentControls"
    }
  



}